# Generated by Django 5.1 on 2024-08-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_onetimepassword_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("email", "email"),
                    ("google", "google"),
                    ("github", "github"),
                ],
                default="email",
                max_length=50,
            ),
        ),
    ]
