# Generated by Django 5.1 on 2024-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Profile Photo"
            ),
        ),
    ]
